name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip python3-setuptools python3-wheel \
            openjdk-11-jdk \
            zip unzip git \
            build-essential \
            libffi-dev libssl-dev \
            libsqlite3-dev \
            libbz2-dev \
            libreadline-dev \
            libncurses5-dev

      - name: Force Java 11 (HARD)
        run: |  
          sudo rm -rf /usr/lib/jvm/temurin-17*
          sudo rm -rf /usr/lib/jvm/temurin-21*
          sudo rm -rf /usr/lib/jvm/temurin-25*
          export JAVA_HOME=/usr/lib/jvm/temurin-11-jdk-amd64
          echo "JAVA_HOME=usr/lib/jvm/temurin-11-jdk-amd64" >> $GITHUB_ENV
          echo "/usr/lib/jvm/temurin-11-jdk-amd64/bin" >> $GITHUB_PATH
          java -version

      - name: Install Buildozer
        run: |
          pip3 install --user buildozer cython==0.29.36
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build APK
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx2g"
        run: |
          export ANDROIDAPI=30
          export ANDROIDMINAPI=21
          export BUILDOZER_ANDROID_GRADLE_CLEAN=0
          export BUILDOZER_ANDROID_GRADLE_DAEMON=0
          buildozer -v android debug --no-clean-build
