name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip python3-setuptools python3-wheel \
          zip unzip git \
          build-essential \
          libffi-dev libssl-dev \
          libsqlite3-dev \
          libbz2-dev \
          libreadline-dev \
          libncurses5-dev

    - name: Set Java 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11

    - name: Install Buildozer
      run: |
        pip3 install --user buildozer==1.5.0 python-for-android==2023.09.16 cython==0.29.36
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Clean buildozer
      run: |
        rm -rf .buildozer

    - name: Fix Gradle
      run: |
        mkdir -p ~/.gradle
        echo "org.gradle.java.home=$JAVA_HOME" >> ~/.gradle/gradle.properties
        echo "org.gradle.jvmargs=-Xmx3g" >> ~/.gradle/gradle.properties

    - name: Force Java 11 only
      run: |
        sudo rm -rf /usr/lib/jvm/temurin-17*
        sudo rm -rf /usr/lib/jvm/temurin-21*
        sudo rm -rf /usr/lib/jvm/temurin-25*
        export JAVA_HOME=/usr/lib/jvm/temurin-11-jdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
        java -version
        
    - name: Build APK
      run: |
        buildozer -v android debug --no-clean-build
